import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F5F5F5]`}
        >
          {/* Navbar */}
          <div className="relative w-full flex justify-center">
            <Navbar />
          </div>

          {/* Page content */}
          <main className="mt-20 p-4">
            {children}
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}
